export const PAYMENT_METHODS = {
    // STRIPE: 'stripe',
    // PAYPAL: 'paypal',
    // RAZORPAY: 'razorpay',
    // MERCADOPAGO: 'mercadopago',
    PAYSTACK: 'paystack',
    // FLUTTERWAVE: 'flutterwave',
    BANK: 'bank',
    // PAYTABS: 'paytabs',
    // SKRILL: 'skrill',
    // COINGATE: 'coingate',
    // PAYFAST: 'payfast',
    // TAP: 'tap',
    // XENDIT: 'xendit',
    // PAYTR: 'paytr',
    // MOLLIE: 'mollie',
    // TOYYIBPAY: 'toyyibpay',
    // BENEFIT: 'benefit',
    // IYZIPAY: 'iyzipay',
    // AAMARPAY: 'aamarpay',
    // MIDTRANS: 'midtrans',
    // YOOKASSA: 'yookassa',
    // NEPALSTE: 'nepalste',
    // PAIEMENT: 'paiement',
    // CINETPAY: 'cinetpay',
    // PAYHERE: 'payhere',
    // FEDAPAY: 'fedapay',
    // AUTHORIZENET: 'authorizenet',
    // KHALTI: 'khalti',
    // EASEBUZZ: 'easebuzz',
    // OZOW: 'ozow',
    // CASHFREE: 'cashfree',
} as const;

export const PAYMENT_METHOD_LABELS = {
    // [PAYMENT_METHODS.STRIPE]: 'Stripe',
    // [PAYMENT_METHODS.PAYPAL]: 'PayPal',
    // [PAYMENT_METHODS.RAZORPAY]: 'Razorpay',
    // [PAYMENT_METHODS.MERCADOPAGO]: 'Mercado Pago',
    [PAYMENT_METHODS.PAYSTACK]: 'Paystack',
    // [PAYMENT_METHODS.FLUTTERWAVE]: 'Flutterwave',
    [PAYMENT_METHODS.BANK]: 'Bank Transfer',
    // [PAYMENT_METHODS.PAYTABS]: 'PayTabs',
    // [PAYMENT_METHODS.SKRILL]: 'Skrill',
    // [PAYMENT_METHODS.COINGATE]: 'CoinGate',
    // [PAYMENT_METHODS.PAYFAST]: 'Payfast',
    // [PAYMENT_METHODS.TAP]: 'Tap',
    // [PAYMENT_METHODS.XENDIT]: 'Xendit',
    // [PAYMENT_METHODS.PAYTR]: 'PayTR',
    // [PAYMENT_METHODS.MOLLIE]: 'Mollie',
    // [PAYMENT_METHODS.TOYYIBPAY]: 'ToyyibPay',
    // [PAYMENT_METHODS.BENEFIT]: 'BenefitPay',
    // [PAYMENT_METHODS.IYZIPAY]: 'IyziPay',
    // [PAYMENT_METHODS.AAMARPAY]: 'AamarPay',
    // [PAYMENT_METHODS.MIDTRANS]: 'Midtrans',
    // [PAYMENT_METHODS.YOOKASSA]: 'YooKassa',
    // [PAYMENT_METHODS.NEPALSTE]: 'Nepalste',
    // [PAYMENT_METHODS.PAIEMENT]: 'Paiement Pro',
    // [PAYMENT_METHODS.CINETPAY]: 'CinetPay',
    // [PAYMENT_METHODS.PAYHERE]: 'PayHere',
    // [PAYMENT_METHODS.FEDAPAY]: 'FedaPay',
    // [PAYMENT_METHODS.AUTHORIZENET]: 'AuthorizeNet',
    // [PAYMENT_METHODS.KHALTI]: 'Khalti',
    // [PAYMENT_METHODS.EASEBUZZ]: 'Easebuzz',
    // [PAYMENT_METHODS.OZOW]: 'Ozow',
    // [PAYMENT_METHODS.CASHFREE]: 'Cashfree',
} as const;

export const PAYMENT_METHOD_HELP_URLS = {
    // [PAYMENT_METHODS.STRIPE]: 'https://dashboard.stripe.com/apikeys',
    // [PAYMENT_METHODS.PAYPAL]: 'https://developer.paypal.com/home',
    // [PAYMENT_METHODS.RAZORPAY]: 'https://dashboard.razorpay.com/',
    // [PAYMENT_METHODS.MERCADOPAGO]: 'https://www.mercadopago.com.br/developers/panel/app',
    [PAYMENT_METHODS.PAYSTACK]: 'https://dashboard.paystack.com/#/settings/developers',
    // [PAYMENT_METHODS.FLUTTERWAVE]: 'https://dashboard.flutterwave.com/settings/apis',
    // [PAYMENT_METHODS.PAYTABS]: 'https://www.paytabs.com/en/support/',
    // [PAYMENT_METHODS.SKRILL]: 'https://www.skrill.com/en/business/',
    // [PAYMENT_METHODS.COINGATE]: 'https://coingate.com/api/docs',
    // [PAYMENT_METHODS.PAYFAST]: 'https://developers.payfast.co.za/',
    // [PAYMENT_METHODS.TAP]: 'https://www.tap.organization/developers/',
    // [PAYMENT_METHODS.XENDIT]: 'https://developers.xendit.co/',
    // [PAYMENT_METHODS.PAYTR]: 'https://www.paytr.com/entegrasyon/',
    // [PAYMENT_METHODS.MOLLIE]: 'https://docs.mollie.com/',
    // [PAYMENT_METHODS.TOYYIBPAY]: 'https://toyyibpay.com/',
    // [PAYMENT_METHODS.BENEFIT]: 'https://www.benefit.bh/en/business/merchant-services/',
    // [PAYMENT_METHODS.IYZIPAY]: 'https://dev.iyzipay.com/',
    // [PAYMENT_METHODS.AAMARPAY]: 'https://aamarpay.com/developer/',
    // [PAYMENT_METHODS.MIDTRANS]: 'https://docs.midtrans.com/',
    // [PAYMENT_METHODS.YOOKASSA]: 'https://yookassa.ru/developers/',
    // [PAYMENT_METHODS.NEPALSTE]: 'https://nepalste.com.np/developer/',
    // [PAYMENT_METHODS.PAIEMENT]: 'https://paiementpro.net/documentation/',
    // [PAYMENT_METHODS.CINETPAY]: 'https://cinetpay.com/documentation/',
    // [PAYMENT_METHODS.PAYHERE]: 'https://www.payhere.lk/developers/',
    // [PAYMENT_METHODS.FEDAPAY]: 'https://docs.fedapay.com/',
    // [PAYMENT_METHODS.AUTHORIZENET]: 'https://developer.authorize.net/',
    // [PAYMENT_METHODS.KHALTI]: 'https://docs.khalti.com/',
    // [PAYMENT_METHODS.EASEBUZZ]: 'https://www.easebuzz.in/developer/',
    // [PAYMENT_METHODS.OZOW]: 'https://developers.ozow.com/',
    // [PAYMENT_METHODS.CASHFREE]: 'https://docs.cashfree.com/',
} as const;
