// Supported languages
const supportedLanguages = [
    'af-za',
    'am-et',
    'ar',
    'ar-ae',
    'ar-dz',
    'ar-eg',
    'ar-lb',
    'ar-ma',
    'ar-qa',
    'ar-sa',
    'bn',
    'bn-bd',
    'bn-in',
    'da',
    'de',
    'de-at',
    'de-ch',
    'de-de',
    'de-lu',
    'en',
    'en-ca',
    'en-gb',
    'en-gh',
    'en-ke',
    'en-ng',
    'en-ug',
    'en-us',
    'en-za',
    'en-zm',
    'en-zw',
    'es',
    'es-ar',
    'es-cl',
    'es-co',
    'es-es',
    'es-mx',
    'es-pe',
    'es-us',
    'fr',
    'fr-be',
    'fr-ca',
    'fr-ch',
    'fr-fr',
    'fr-lu',
    'ga-ie',
    'ha',
    'ha-gh',
    'ha-ne',
    'ha-ng',
    'he-il',
    'hi-in',
    'it',
    'it-it',
    'ja-jp',
    'ko-kr',
    'pl-pl',
    'pt',
    'pt-br',
    'pt-mz',
    'pt-pt',
    'ru',
    'ru-kz',
    'ru-ru',
    'ru-ua',
    'sn-zw',
    'so-so',
    'sw',
    'sw-ke',
    'sw-tz',
    'tr-tr',
    'xh-za',
    'yo-ng',
    'zh-cn',
    'zh-tw',
    'zu-za',
];

// Supported rtl languages
const rtlLanguages = ['ar', 'ar-sa', 'ar-ae', 'ar-eg', 'ar-ma', 'ar-dz', 'ar-qa', 'ar-lb', 'he-il', 'fa', 'ur'];

// Supported languages with language codes as keys and values as objects containing the native language names
const supportedLanguagesWithNativeNames = Object.freeze({
    'af-za': { nativeName: 'Afrikaans (Suid-Afrika)' },
    'am-et': { nativeName: 'አማርኛ (ኢትዮጵያ)' },
    ar: { nativeName: 'العربية' },
    'ar-ae': { nativeName: 'العربية (الإمارات العربية المتحدة)' },
    'ar-eg': { nativeName: 'العربية (مصر)' },
    'ar-lb': { nativeName: 'العربية (لبنان)' },
    'ar-ma': { nativeName: 'العربية (المغرب)' },
    'ar-qa': { nativeName: 'العربية (قطر)' },
    'ar-sa': { nativeName: 'العربية (المملكة العربية السعودية)' },
    bn: { nativeName: 'বাংলা' },
    'bn-bd': { nativeName: 'বাংলা (বাংলাদেশ)' },
    'bn-in': { nativeName: 'বাংলা (ভারত)' },
    da: { nativeName: 'Dansk (Danmark)' },
    de: { nativeName: 'Deutsch' },
    'de-at': { nativeName: 'Deutsch (Österreich)' },
    'de-ch': { nativeName: 'Deutsch (Schweiz)' },
    'de-de': { nativeName: 'Deutsch (Deutschland)' },
    'de-lu': { nativeName: 'Deutsch (Luxemburg)' },
    en: { nativeName: 'English' },
    'en-ca': { nativeName: 'English (Canada)' },
    'en-gb': { nativeName: 'English (United Kingdom)' },
    'en-gh': { nativeName: 'English (Ghana)' },
    'en-ke': { nativeName: 'English (Kenya)' },
    'en-ng': { nativeName: 'English (Nigeria)' },
    'en-ug': { nativeName: 'English (Uganda)' },
    'en-us': { nativeName: 'English (United States)' },
    'en-za': { nativeName: 'English (South Africa)' },
    'en-zm': { nativeName: 'English (Zambia)' },
    'en-zw': { nativeName: 'English (Zimbabwe)' },
    es: { nativeName: 'Español' },
    'es-ar': { nativeName: 'Español (Argentina)' },
    'es-cl': { nativeName: 'Español (Chile)' },
    'es-co': { nativeName: 'Español (Colombia)' },
    'es-es': { nativeName: 'Español (España)' },
    'es-mx': { nativeName: 'Español (México)' },
    'es-pe': { nativeName: 'Español (Perú)' },
    'es-us': { nativeName: 'Español (Estados Unidos)' },
    fr: { nativeName: 'Français' },
    'fr-be': { nativeName: 'Français (Belgique)' },
    'fr-ca': { nativeName: 'Français (Canada)' },
    'fr-ch': { nativeName: 'Français (Suisse)' },
    'fr-fr': { nativeName: 'Français (France)' },
    'fr-lu': { nativeName: 'Français (Luxembourg)' },
    'ga-ie': { nativeName: 'Gaeilge (Éire)' },
    ha: { nativeName: 'هَوُسَ' },
    'ha-gh': { nativeName: 'Hausa (Ghana)' },
    'ha-ne': { nativeName: 'Hausa (Nijar)' },
    'ha-ng': { nativeName: 'Hausa (Nijeriya)' },
    'he-il': { nativeName: 'עברית (ישראל)' },
    'hi-in': { nativeName: 'हिंदी भारत)' },
    it: { nativeName: 'Italiano' },
    'it-it': { nativeName: 'Italiano (Italia)' },
    'ja-jp': { nativeName: '日本語 (日本)' },
    'ko-kr': { nativeName: '한국어(한국)' },
    'pl-pl': { nativeName: 'Polski (Polska)' },
    pt: { nativeName: 'Português' },
    'pt-br': { nativeName: 'Português (Brasil)' },
    'pt-mz': { nativeName: 'Português (Moçambique)' },
    'pt-pt': { nativeName: 'Português (Portugal)' },
    ru: { nativeName: 'Pусский' },
    'ru-kz': { nativeName: 'Русский (Казахстан)' },
    'ru-ru': { nativeName: 'Русский (Россия)' },
    'ru-ua': { nativeName: 'Русский (Украина)' },
    'sn-zw': { nativeName: 'Shona (Zimbabwe)' },
    'so-so': { nativeName: 'Soomaali (Soomaaliya)' },
    sw: { nativeName: 'Kiswahili' },
    'sw-ke': { nativeName: 'Kiswahili (Kenya)' },
    'sw-tz': { nativeName: 'Kiswahili (Tanzania)' },
    'tr-tr': { nativeName: 'Türkçe (Türkiye)' },
    'xh-za': { nativeName: 'IsiXhosa (eMzantsi Afrika)' },
    'yo-ng': { nativeName: 'Yorùbá (Nigeria)' },
    'zh-cn': { nativeName: '简体中文' },
    'zh-tw': { nativeName: '繁體中文' },
    'zu-za': { nativeName: 'IsiZulu (Ningizimu Afrika)' },
});

export { rtlLanguages, supportedLanguages, supportedLanguagesWithNativeNames };
