<?php

return [
    'super_admin' => [
        'dashboard',
        'users',
        'roles',
        'permissions',
        'organizations',
        'plans',
        'plan_requests',
        'plan_orders',
        'domain_requests',
        'currencies',
        'referral',
        'coupons',
        'appointments',
        'businesses',
        'settings',
    ],

    'organization' => [
        'dashboard',
        'users',
        'roles',
        'appointments',
        'media',
        // 'currencies',
        'webhooks',
        'taxes',
        'brands',
        'categories',
        'products',
        'contacts',
        'accounts',
        'account_types',
        'account_industries',
        'lead_statuses',
        'lead_sources',
        'leads',
        'opportunity_stages',
        'opportunity_sources',
        'opportunities',
        'campaign_types',
        'target_lists',
        'campaigns',
        'shipping_provider_types',
        'cases',
        'quotes',
        'sales_orders',
        'invoices',
        'delivery_orders',
        'return_orders',
        'purchase_orders',
        'receipt_orders',
        'projects',
        'task_statuses',
        'project_tasks',
        'meetings',
        'calls',
        'document_folders',
        'document_types',
        'documents',
        'stream',
        'notes',
        'announcements',
        'announcement_categories',
        // 'notification_templates',
        'reports',
    ],
];
