<?php

return [
    'super_admin' => [
        'dashboard',
        'users',
        'roles',
        'permissions',
        'organizations',
        'plans',
        'plan-requests',
        'plan-orders',
        'currencies',
        'referral',
        'coupons',
        'appointments',
        'organizations',
        'settings',
    ],

    'organization' => [
        'dashboard',
        'users',
        'roles',
        'appointments',
        'media',
        // 'currencies',
        'webhooks',
        'taxes',
        'brands',
        'categories',
        'products',
        'contacts',
        'accounts',
        'account-types',
        'account-industries',
        'lead-statuses',
        'lead-sources',
        'leads',
        'opportunity-stages',
        'opportunity-sources',
        'opportunities',
        'campaign-types',
        'target-lists',
        'campaigns',
        'shipping-provider-types',
        'cases',
        'quotes',
        'sales-orders',
        'invoices',
        'delivery-orders',
        'return-orders',
        'purchase-orders',
        'receipt-orders',
        'projects',
        'task-statuses',
        'project-tasks',
        'meetings',
        'calls',
        'document-folders',
        'document-types',
        'documents',
        'stream',
        'notes',
        'announcements',
        'announcement-categories',
        // 'notification-templates',
        'reports',
    ],
];
